openapi: 3.0.3
info:
  title: LLM Ops Training API
  version: 0.1.0
servers:
  - url: https://{env}.llm-ops.local/llm-ops/v1
    variables:
      env:
        default: dev
        enum: [dev, stg, prod]
paths:
  /training/jobs:
    post:
      summary: Submit a fine-tuning or distributed training job
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TrainingJobRequest"
      responses:
        "200":
          description: Job accepted into scheduler
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnvelopeTrainingJob"
  /training/jobs/{jobId}:
    get:
      summary: Retrieve training job status and experiment metadata
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Job status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnvelopeTrainingJob"
    delete:
      summary: Cancel a queued or running job
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Cancellation acknowledged
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnvelopeTrainingJob"
  /training/jobs/{jobId}/metrics:
    post:
      summary: Record a metric for a training job (called from training pod)
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecordMetricRequest"
      responses:
        "200":
          description: Metric recorded successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnvelopeMetric"
  /training/experiments/{jobId}:
    get:
      summary: Get experiment metrics for a training job
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Experiment metrics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnvelopeExperiment"
components:
  schemas:
    EnvelopeTrainingJob:
      type: object
      properties:
        status:
          type: string
          enum: [success, fail]
        message:
          type: string
        data:
          $ref: "#/components/schemas/TrainingJob"
    TrainingJobRequest:
      type: object
      required:
        - modelId
        - datasetId
        - jobType
        - resourceProfile
      properties:
        modelId:
          type: string
        datasetId:
          type: string
        jobType:
          type: string
          enum: [finetune, from_scratch, pretrain, distributed]
        hyperparameters:
          type: object
        resourceProfile:
          type: object
          required: [gpuCount, gpuType, maxDuration]
          properties:
            gpuCount:
              type: integer
              minimum: 1
            gpuType:
              type: string
            maxDuration:
              type: integer
              description: Minutes before timeout
        retryPolicy:
          type: object
          properties:
            maxRetries:
              type: integer
              default: 3
            backoffSeconds:
              type: integer
        notifications:
          type: object
          properties:
            onStart:
              type: array
              items:
                type: string
            onCompletion:
              type: array
              items:
                type: string
        apiBaseUrl:
          type: string
          description: API base URL for training pod to record metrics. If not provided, uses server configuration. For local development with minikube, use http://host.minikube.internal:8000/llm-ops/v1
          example: "http://host.minikube.internal:8000/llm-ops/v1"
    TrainingJob:
      allOf:
        - $ref: "#/components/schemas/TrainingJobRequest"
        - type: object
          properties:
            id:
              type: string
            status:
              type: string
              enum: [queued, running, succeeded, failed, cancelled]
            submittedAt:
              type: string
              format: date-time
            startedAt:
              type: string
              format: date-time
            completedAt:
              type: string
              format: date-time
            experimentUrl:
              type: string
    RecordMetricRequest:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
          description: Metric name (e.g., 'loss', 'accuracy')
        value:
          type: number
          description: Metric value
        unit:
          type: string
          description: Metric unit (e.g., 'percentage', 'seconds')
    ExperimentMetric:
      type: object
      properties:
        id:
          type: string
        trainingJobId:
          type: string
        name:
          type: string
        value:
          type: number
        unit:
          type: string
        recordedAt:
          type: string
          format: date-time
    EnvelopeMetric:
      type: object
      properties:
        status:
          type: string
          enum: [success, fail]
        message:
          type: string
        data:
          $ref: "#/components/schemas/ExperimentMetric"
    Experiment:
      type: object
      properties:
        jobId:
          type: string
        metrics:
          type: array
          items:
            $ref: "#/components/schemas/ExperimentMetric"
    EnvelopeExperiment:
      type: object
      properties:
        status:
          type: string
          enum: [success, fail]
        message:
          type: string
        data:
          $ref: "#/components/schemas/Experiment"

