openapi: 3.0.3
info:
  title: Experiment Tracking Integration API
  description: |
    API endpoints for integrating open-source experiment tracking systems (MLflow, W&B, etc.)
    with the LLM Ops platform. All endpoints maintain the standard `/llm-ops/v1` contract.
  version: 1.0.0
  contact:
    name: LLM Ops Platform Team

servers:
  - url: http://localhost:8000/llm-ops/v1
    description: Local development server
  - url: https://api.example.com/llm-ops/v1
    description: Production server

paths:
  /training/jobs/{jobId}/experiment-run:
    get:
      summary: Get experiment run for training job
      description: Retrieves the experiment run linked to a training job from the open-source tracking system.
      operationId: getExperimentRun
      tags:
        - Experiment Tracking
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Training job ID
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Experiment run retrieved successfully
                  data:
                    $ref: '#/components/schemas/ExperimentRun'
        '404':
          description: Experiment run not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: Create experiment run for training job
      description: Creates an experiment run in the open-source tracking system and links it to a training job.
      operationId: createExperimentRun
      tags:
        - Experiment Tracking
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Training job ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExperimentRunRequest'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Experiment run created successfully
                  data:
                    $ref: '#/components/schemas/ExperimentRun'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /training/jobs/{jobId}/experiment-run/metrics:
    post:
      summary: Log metrics to experiment run
      description: Logs metrics to the experiment run in the open-source tracking system.
      operationId: logExperimentMetrics
      tags:
        - Experiment Tracking
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Training job ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogMetricsRequest'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Metrics logged successfully
                  data:
                    type: object
        '404':
          description: Experiment run not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /experiments/search:
    post:
      summary: Search experiments
      description: Searches experiments in the open-source tracking system with filters.
      operationId: searchExperiments
      tags:
        - Experiment Tracking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchExperimentsRequest'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Experiments retrieved successfully
                  data:
                    type: object
                    properties:
                      experiments:
                        type: array
                        items:
                          $ref: '#/components/schemas/ExperimentRun'
                      total:
                        type: integer
                        example: 42
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ExperimentRun:
      type: object
      properties:
        id:
          type: string
          format: uuid
        training_job_id:
          type: string
          format: uuid
        tracking_system:
          type: string
          example: mlflow
        tracking_run_id:
          type: string
          example: abc123def456
        experiment_name:
          type: string
          example: fine-tuning-experiment
        run_name:
          type: string
          example: run-2025-01-27
        parameters:
          type: object
          additionalProperties: true
        metrics:
          type: object
          additionalProperties: true
        artifact_uris:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [running, completed, failed, killed]
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    CreateExperimentRunRequest:
      type: object
      required:
        - experiment_name
        - tracking_system
      properties:
        experiment_name:
          type: string
          example: fine-tuning-experiment
        run_name:
          type: string
          example: run-2025-01-27
        tracking_system:
          type: string
          enum: [mlflow, wandb]
          example: mlflow
        parameters:
          type: object
          additionalProperties: true

    LogMetricsRequest:
      type: object
      required:
        - metrics
      properties:
        metrics:
          type: object
          additionalProperties:
            type: number
          example:
            loss: 0.5
            accuracy: 0.95
            learning_rate: 0.001

    SearchExperimentsRequest:
      type: object
      properties:
        model_id:
          type: string
          format: uuid
        dataset_id:
          type: string
          format: uuid
        experiment_name:
          type: string
        status:
          type: string
          enum: [running, completed, failed, killed]
        start_date:
          type: string
          format: date-time
        end_date:
          type: string
          format: date-time
        limit:
          type: integer
          default: 50
          maximum: 1000
        offset:
          type: integer
          default: 0

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: Error description
        data:
          type: object
          nullable: true

